from typing import Protocol, runtime_checkable


@runtime_checkable
class BlobStorage(Protocol):
    async def put(self, key: str, content: bytes, content_type: str = "") -> None: ...
    async def get(self, key: str) -> bytes | None: ...
    async def delete(self, key: str) -> None: ...
    async def signed_url(self, key: str, expires_in: int = 3600) -> str: ...
