"""Contratos de integración con servicios externos."""

from kosmo.contracts.integrations.deployment import (
    DeploymentOAuthToken,
    DeploymentProvider,
    DeploymentProviderPort,
    DeploymentStatus,
    EnvironmentVariable,
    PortSpec,
    ProjectDeployment,
    ProjectDeploymentRepository,
    UserDeploymentIntegration,
    UserDeploymentIntegrationRepository,
    VolumeConfig,
)
from kosmo.contracts.integrations.git import GitWorkspacePort
from kosmo.contracts.integrations.github import (
    CodeSyncLog,
    CodeSyncStatus,
    GitHubApiError,
    GitHubAuthenticationError,
    GitHubClientPort,
    GitHubOAuthToken,
    GitHubPermissionError,
    GitHubRateLimitError,
    GitHubRepository,
    GitHubRepositoryAlreadyExistsError,
    GitHubResourceNotFoundError,
    GitHubSyncStatus,
    GitHubUser,
    ProjectGitHubIntegration,
    ProjectGitHubIntegrationRepository,
    UserGitHubIntegration,
    UserGitHubIntegrationRepository,
)
from kosmo.contracts.integrations.user_integration import (
    IntegrationProvider,
    UserIntegration,
    UserIntegrationRepository,
)

__all__ = [
    "GitHubOAuthToken",
    "GitHubUser",
    "GitHubRepository",
    "GitHubApiError",
    "GitHubAuthenticationError",
    "GitHubPermissionError",
    "GitHubRateLimitError",
    "GitHubResourceNotFoundError",
    "GitHubRepositoryAlreadyExistsError",
    "GitHubClientPort",
    "IntegrationProvider",
    "UserIntegration",
    "UserIntegrationRepository",
    "UserGitHubIntegration",
    "UserGitHubIntegrationRepository",
    "GitHubSyncStatus",
    "ProjectGitHubIntegration",
    "ProjectGitHubIntegrationRepository",
    "CodeSyncStatus",
    "CodeSyncLog",
    "GitWorkspacePort",
    "DeploymentProvider",
    "DeploymentStatus",
    "VolumeConfig",
    "PortSpec",
    "EnvironmentVariable",
    "DeploymentOAuthToken",
    "UserDeploymentIntegration",
    "ProjectDeployment",
    "UserDeploymentIntegrationRepository",
    "ProjectDeploymentRepository",
    "DeploymentProviderPort",
]
