from __future__ import annotations

from typing import Protocol

from kosmo.contracts.pipeline.pipeline_state import KOSMOPipelineState
from kosmo.contracts.sdd.ids import PipelineId, ProjectId


class PipelineRepository(Protocol):
    async def get(self, project_id: ProjectId) -> KOSMOPipelineState | None: ...
    async def save(self, state: KOSMOPipelineState) -> KOSMOPipelineState: ...
    async def get_by_id(self, pipeline_id: PipelineId) -> KOSMOPipelineState | None: ...
    async def delete(self, project_id: ProjectId) -> None: ...
